### ISSUE TITLE
Playwright E2E Testing Setup

### ISSUE THREAD

**Issue by benjaminstrasser** [codingcommons/tiny-tms#10]
We're looking at adding Playwright for automated UI testing across browsers. Cypress is another option if it fits our needs better.

**What we need:**
- Set up Playwright for end-to-end testing.
- Consider Cypress as an alternative.
- Create a test/reset endpoint to reset the database, secured with an environment variable and a JWT.

**Benefits:**
- Better test coverage across browsers.
- Easier to manage tests with a clean database state.

**Security for test/reset endpoint:**
- Only enable in test environments, controlled by an environment variable.
- Access requires a JWT.

Open to other ideas on how to implement or secure the test/reset endpoint. Let's discuss the best tool for our testing and how to set up the endpoint.

**Comment by sjaghori** [comment]
We need to include one simple test that logs into the app. With that we cover a lot already.

**Comment by sjaghori** [comment]
https://github.com/codingcommons/tiny-tms/pull/97
